"""Public exports, loaded only when requested to keep API startup lightweight."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from openakita.core.confirmation_state import (
        PendingRiskConfirmation,
        PendingRiskConfirmationStore,
        get_confirmation_store,
    )

    from .audit import AuditLogger, get_audit_logger, reset_audit_logger
    from .brain import Brain, SupervisorBrain
    from .brain import Context as BrainContext
    from .brain import Response as BrainResponse
    from .capabilities import (
        CapabilityDescriptor,
        CapabilityKind,
        CapabilityOrigin,
        CapabilityVisibility,
        build_capability_id,
        build_namespace,
        normalize_slug,
    )
    from .confirmation import (
        ConfirmationDecision,
        normalize_confirmation_answer,
    )
    from .context import (
        CHARS_PER_TOKEN,
        CHUNK_MAX_TOKENS,
        CONTEXT_BOUNDARY_MARKER,
        DEFAULT_MAX_CONTEXT_TOKENS,
        ContextManager,
        ContextPressure,
        estimate_tokens,
        get_max_context_tokens,
    )
    from .core import Agent, PromptStrategy, get_primary_agent, set_primary_agent
    from .desktop_notify import (
        notify_task_completed,
        notify_task_completed_async,
        send_desktop_notification,
        send_desktop_notification_async,
    )
    from .docker_backend import (
        DockerBackend,
        DockerConfig,
        DockerResult,
        configure_docker,
        get_docker_backend,
    )
    from .domain_allowlist import Decision, DomainAllowlist, get_domain_allowlist
    from .errors import UserCancelledError
    from .file_history import (
        HISTORY_BASE_DIR,
        MAX_SNAPSHOTS,
        BackupInfo,
        FileHistoryManager,
        FileSnapshot,
    )
    from .hooks import (
        CallbackHook,
        HookEvent,
        HookExecutor,
        HookHandler,
        HookResult,
        ShellHook,
        get_hook_executor,
        set_hook_executor,
    )
    from .identity import Identity
    from .loop_budget import (
        READONLY_EXPLORATION_TOOLS,
        LoopBudgetDecision,
        LoopBudgetGuard,
    )
    from .lsp_feedback import (
        Diagnostic,
        DiagnosticBackend,
        DiagnosticReport,
        LSPFeedbackCollector,
        RuffBackend,
        TypeScriptBackend,
    )
    from .output_formatter import (
        JSONFormatter,
        OutputFormatter,
        StreamJSONFormatter,
        TextFormatter,
        create_formatter,
    )
    from .output_guard import (
        CODE_EXEC_TOOLS,
        DISCLAIMER_TEXT,
        detect_numeric_output,
        detect_numeric_task,
        validate_no_fabricated_numbers,
    )
    from .pending_approvals import (
        PendingApproval,
        PendingApprovalsStore,
        get_pending_approvals_store,
        reset_pending_approvals_store,
    )
    from .permission import (
        ASK_MODE_RULESET,
        COORDINATOR_MODE_RULESET,
        DEFAULT_RULESET,
        PLAN_MODE_RULESET,
        DeniedError,
        PermissionDecision,
        PermissionRule,
        Ruleset,
        check_mode_permission,
        check_path,
        check_permission,
    )
    from .persona import (
        PERSONA_DIMENSIONS,
        MergedPersona,
        PersonaManager,
        PersonaTrait,
        persist_trait_to_memory,
    )
    from .ralph import RalphLoop, StopHook, Task, TaskResult, TaskStatus
    from .reasoning import Checkpoint, DecisionType, ReasoningEngine
    from .reasoning import Decision as ReasoningDecision
    from .resource_budget import (
        BudgetAction,
        BudgetConfig,
        BudgetExceeded,
        BudgetStatus,
        ResourceBudget,
        create_budget_from_settings,
    )
    from .sandbox import (
        CommandSandbox,
        SandboxExecutor,
        SandboxPolicy,
        SandboxResult,
        SandboxVerdict,
        get_sandbox_executor,
    )
    from .security_actions import (
        add_security_allowlist_entry,
        execute_controlled_action,
        list_security_allowlist,
        list_skill_external_allowlist,
        maybe_broadcast_death_switch_reset,
        maybe_refresh_skills,
        remove_security_allowlist_entry,
        reset_death_switch,
        set_skill_external_allowlist,
    )
    from .skill_manager import (
        SKILL_GIT_CLONE_TIMEOUT_SECONDS,
        SKILL_INSTALL_CIRCUIT_COOLDOWN_SECONDS,
        SKILL_INSTALL_CIRCUIT_THRESHOLD,
        SkillManager,
    )
    from .sse_replay import (
        DEFAULT_MAXLEN,
        DEFAULT_TTL_SECONDS,
        MAX_SESSIONS,
        SSEEvent,
        SSESession,
        SSESessionRegistry,
        format_sse_frame,
        get_registry,
        parse_last_event_id,
        reset_registry_for_testing,
    )
    from .token_budget import TokenBudget, parse_token_budget
    from .tool_result_budget import (
        DEFAULT_MAX_RESULT_CHARS,
        OVERFLOW_DIR,
        truncate_tool_result,
    )
    from .tools import (
        DEFAULT_TOOL_RESULT_MAX_CHARS,
        MAX_TOOL_RESULT_CHARS,
        OVERFLOW_MARKER,
        ToolExecutor,
        ToolResultWithHint,
        ToolSkipped,
        save_overflow,
        smart_truncate,
    )
    from .trait_miner import (
        ANSWER_ANALYSIS_PROMPT,
        ANSWER_ANALYSIS_SYSTEM,
        TRAIT_MINING_PROMPT,
        TRAIT_MINING_SYSTEM,
        TraitMiner,
    )
    from .trusted_paths import (
        SESSION_KEY,
        clear_session_trust,
        consume_session_trust,
        get_session_overrides,
        grant_session_trust,
        is_trusted_workspace_path,
    )
    from .ui_confirm_bus import UIConfirmBus, get_ui_confirm_bus, reset_ui_confirm_bus
    from .user_profile import (
        USER_PROFILE_ITEMS,
        USER_PROFILE_KEY_ALIASES,
        UserProfileItem,
        UserProfileManager,
        UserProfileState,
        get_profile_manager,
        resolve_profile_key,
    )
    from .validators import (
        BaseValidator,
        ValidationContext,
        ValidationReport,
        ValidationResult,
        ValidatorOutput,
        ValidatorRegistry,
        create_default_registry,
    )
    from .working_facts import (
        extract_working_facts,
        format_working_facts,
        merge_working_facts,
    )

__all__ = [
    "ANSWER_ANALYSIS_PROMPT",
    "ANSWER_ANALYSIS_SYSTEM",
    "ASK_MODE_RULESET",
    "Agent",
    "AuditLogger",
    "BackupInfo",
    "BaseValidator",
    "Brain",
    "BrainContext",
    "BrainResponse",
    "BudgetAction",
    "BudgetConfig",
    "BudgetExceeded",
    "BudgetStatus",
    "CHARS_PER_TOKEN",
    "CHUNK_MAX_TOKENS",
    "CODE_EXEC_TOOLS",
    "CONTEXT_BOUNDARY_MARKER",
    "COORDINATOR_MODE_RULESET",
    "CallbackHook",
    "CapabilityDescriptor",
    "CapabilityKind",
    "CapabilityOrigin",
    "CapabilityVisibility",
    "Checkpoint",
    "CommandSandbox",
    "ConfirmationDecision",
    "ContextManager",
    "ContextPressure",
    "DEFAULT_MAX_CONTEXT_TOKENS",
    "DEFAULT_MAX_RESULT_CHARS",
    "DEFAULT_MAXLEN",
    "DEFAULT_RULESET",
    "DEFAULT_TOOL_RESULT_MAX_CHARS",
    "DEFAULT_TTL_SECONDS",
    "DISCLAIMER_TEXT",
    "Decision",
    "DecisionType",
    "DeniedError",
    "Diagnostic",
    "DiagnosticBackend",
    "DiagnosticReport",
    "DockerBackend",
    "DockerConfig",
    "DockerResult",
    "DomainAllowlist",
    "FileHistoryManager",
    "FileSnapshot",
    "HISTORY_BASE_DIR",
    "HookEvent",
    "HookExecutor",
    "HookHandler",
    "HookResult",
    "Identity",
    "JSONFormatter",
    "LSPFeedbackCollector",
    "LoopBudgetDecision",
    "LoopBudgetGuard",
    "MAX_SESSIONS",
    "MAX_SNAPSHOTS",
    "MAX_TOOL_RESULT_CHARS",
    "MergedPersona",
    "OVERFLOW_DIR",
    "OVERFLOW_MARKER",
    "OutputFormatter",
    "PERSONA_DIMENSIONS",
    "PLAN_MODE_RULESET",
    "PendingApproval",
    "PendingApprovalsStore",
    "PendingRiskConfirmation",
    "PendingRiskConfirmationStore",
    "PermissionDecision",
    "PermissionRule",
    "PersonaManager",
    "PersonaTrait",
    "PromptStrategy",
    "READONLY_EXPLORATION_TOOLS",
    "RalphLoop",
    "ReasoningDecision",
    "ReasoningEngine",
    "ResourceBudget",
    "RuffBackend",
    "Ruleset",
    "SESSION_KEY",
    "SKILL_GIT_CLONE_TIMEOUT_SECONDS",
    "SKILL_INSTALL_CIRCUIT_COOLDOWN_SECONDS",
    "SKILL_INSTALL_CIRCUIT_THRESHOLD",
    "SSEEvent",
    "SSESession",
    "SSESessionRegistry",
    "SandboxExecutor",
    "SandboxPolicy",
    "SandboxResult",
    "SandboxVerdict",
    "ShellHook",
    "SkillManager",
    "StopHook",
    "StreamJSONFormatter",
    "SupervisorBrain",
    "TRAIT_MINING_PROMPT",
    "TRAIT_MINING_SYSTEM",
    "Task",
    "TaskResult",
    "TaskStatus",
    "TextFormatter",
    "TokenBudget",
    "ToolExecutor",
    "ToolResultWithHint",
    "ToolSkipped",
    "TraitMiner",
    "TypeScriptBackend",
    "UIConfirmBus",
    "USER_PROFILE_ITEMS",
    "USER_PROFILE_KEY_ALIASES",
    "UserCancelledError",
    "UserProfileItem",
    "UserProfileManager",
    "UserProfileState",
    "ValidationContext",
    "ValidationReport",
    "ValidationResult",
    "ValidatorOutput",
    "ValidatorRegistry",
    "add_security_allowlist_entry",
    "build_capability_id",
    "build_namespace",
    "check_mode_permission",
    "check_path",
    "check_permission",
    "clear_session_trust",
    "configure_docker",
    "consume_session_trust",
    "create_budget_from_settings",
    "create_default_registry",
    "create_formatter",
    "detect_numeric_output",
    "detect_numeric_task",
    "estimate_tokens",
    "execute_controlled_action",
    "extract_working_facts",
    "format_sse_frame",
    "format_working_facts",
    "get_audit_logger",
    "get_confirmation_store",
    "get_docker_backend",
    "get_domain_allowlist",
    "get_hook_executor",
    "get_max_context_tokens",
    "get_pending_approvals_store",
    "get_primary_agent",
    "get_profile_manager",
    "get_registry",
    "get_sandbox_executor",
    "get_session_overrides",
    "get_ui_confirm_bus",
    "grant_session_trust",
    "is_trusted_workspace_path",
    "list_security_allowlist",
    "list_skill_external_allowlist",
    "maybe_broadcast_death_switch_reset",
    "maybe_refresh_skills",
    "merge_working_facts",
    "normalize_confirmation_answer",
    "normalize_slug",
    "notify_task_completed",
    "notify_task_completed_async",
    "parse_last_event_id",
    "parse_token_budget",
    "persist_trait_to_memory",
    "remove_security_allowlist_entry",
    "reset_audit_logger",
    "reset_death_switch",
    "reset_pending_approvals_store",
    "reset_registry_for_testing",
    "reset_ui_confirm_bus",
    "resolve_profile_key",
    "save_overflow",
    "send_desktop_notification",
    "send_desktop_notification_async",
    "set_hook_executor",
    "set_primary_agent",
    "set_skill_external_allowlist",
    "smart_truncate",
    "truncate_tool_result",
    "validate_no_fabricated_numbers",
]

_EXPORTS = {
    "ANSWER_ANALYSIS_PROMPT": (".trait_miner", "ANSWER_ANALYSIS_PROMPT"),
    "ANSWER_ANALYSIS_SYSTEM": (".trait_miner", "ANSWER_ANALYSIS_SYSTEM"),
    "ASK_MODE_RULESET": (".permission", "ASK_MODE_RULESET"),
    "Agent": (".core", "Agent"),
    "AuditLogger": (".audit", "AuditLogger"),
    "BackupInfo": (".file_history", "BackupInfo"),
    "BaseValidator": (".validators", "BaseValidator"),
    "Brain": (".brain", "Brain"),
    "BrainContext": (".brain", "Context"),
    "BrainResponse": (".brain", "Response"),
    "BudgetAction": (".resource_budget", "BudgetAction"),
    "BudgetConfig": (".resource_budget", "BudgetConfig"),
    "BudgetExceeded": (".resource_budget", "BudgetExceeded"),
    "BudgetStatus": (".resource_budget", "BudgetStatus"),
    "CHARS_PER_TOKEN": (".context", "CHARS_PER_TOKEN"),
    "CHUNK_MAX_TOKENS": (".context", "CHUNK_MAX_TOKENS"),
    "CODE_EXEC_TOOLS": (".output_guard", "CODE_EXEC_TOOLS"),
    "CONTEXT_BOUNDARY_MARKER": (".context", "CONTEXT_BOUNDARY_MARKER"),
    "COORDINATOR_MODE_RULESET": (".permission", "COORDINATOR_MODE_RULESET"),
    "CallbackHook": (".hooks", "CallbackHook"),
    "CapabilityDescriptor": (".capabilities", "CapabilityDescriptor"),
    "CapabilityKind": (".capabilities", "CapabilityKind"),
    "CapabilityOrigin": (".capabilities", "CapabilityOrigin"),
    "CapabilityVisibility": (".capabilities", "CapabilityVisibility"),
    "Checkpoint": (".reasoning", "Checkpoint"),
    "CommandSandbox": (".sandbox", "CommandSandbox"),
    "ConfirmationDecision": (".confirmation", "ConfirmationDecision"),
    "ContextManager": (".context", "ContextManager"),
    "ContextPressure": (".context", "ContextPressure"),
    "DEFAULT_MAXLEN": (".sse_replay", "DEFAULT_MAXLEN"),
    "DEFAULT_MAX_CONTEXT_TOKENS": (".context", "DEFAULT_MAX_CONTEXT_TOKENS"),
    "DEFAULT_MAX_RESULT_CHARS": (".tool_result_budget", "DEFAULT_MAX_RESULT_CHARS"),
    "DEFAULT_RULESET": (".permission", "DEFAULT_RULESET"),
    "DEFAULT_TOOL_RESULT_MAX_CHARS": (".tools", "DEFAULT_TOOL_RESULT_MAX_CHARS"),
    "DEFAULT_TTL_SECONDS": (".sse_replay", "DEFAULT_TTL_SECONDS"),
    "DISCLAIMER_TEXT": (".output_guard", "DISCLAIMER_TEXT"),
    "Decision": (".domain_allowlist", "Decision"),
    "DecisionType": (".reasoning", "DecisionType"),
    "DeniedError": (".permission", "DeniedError"),
    "Diagnostic": (".lsp_feedback", "Diagnostic"),
    "DiagnosticBackend": (".lsp_feedback", "DiagnosticBackend"),
    "DiagnosticReport": (".lsp_feedback", "DiagnosticReport"),
    "DockerBackend": (".docker_backend", "DockerBackend"),
    "DockerConfig": (".docker_backend", "DockerConfig"),
    "DockerResult": (".docker_backend", "DockerResult"),
    "DomainAllowlist": (".domain_allowlist", "DomainAllowlist"),
    "FileHistoryManager": (".file_history", "FileHistoryManager"),
    "FileSnapshot": (".file_history", "FileSnapshot"),
    "HISTORY_BASE_DIR": (".file_history", "HISTORY_BASE_DIR"),
    "HookEvent": (".hooks", "HookEvent"),
    "HookExecutor": (".hooks", "HookExecutor"),
    "HookHandler": (".hooks", "HookHandler"),
    "HookResult": (".hooks", "HookResult"),
    "Identity": (".identity", "Identity"),
    "JSONFormatter": (".output_formatter", "JSONFormatter"),
    "LSPFeedbackCollector": (".lsp_feedback", "LSPFeedbackCollector"),
    "LoopBudgetDecision": (".loop_budget", "LoopBudgetDecision"),
    "LoopBudgetGuard": (".loop_budget", "LoopBudgetGuard"),
    "MAX_SESSIONS": (".sse_replay", "MAX_SESSIONS"),
    "MAX_SNAPSHOTS": (".file_history", "MAX_SNAPSHOTS"),
    "MAX_TOOL_RESULT_CHARS": (".tools", "MAX_TOOL_RESULT_CHARS"),
    "MergedPersona": (".persona", "MergedPersona"),
    "OVERFLOW_DIR": (".tool_result_budget", "OVERFLOW_DIR"),
    "OVERFLOW_MARKER": (".tools", "OVERFLOW_MARKER"),
    "OutputFormatter": (".output_formatter", "OutputFormatter"),
    "PERSONA_DIMENSIONS": (".persona", "PERSONA_DIMENSIONS"),
    "PLAN_MODE_RULESET": (".permission", "PLAN_MODE_RULESET"),
    "PendingApproval": (".pending_approvals", "PendingApproval"),
    "PendingApprovalsStore": (".pending_approvals", "PendingApprovalsStore"),
    "PendingRiskConfirmation": ("openakita.core.confirmation_state", "PendingRiskConfirmation"),
    "PendingRiskConfirmationStore": (
        "openakita.core.confirmation_state",
        "PendingRiskConfirmationStore",
    ),
    "PermissionDecision": (".permission", "PermissionDecision"),
    "PermissionRule": (".permission", "PermissionRule"),
    "PersonaManager": (".persona", "PersonaManager"),
    "PersonaTrait": (".persona", "PersonaTrait"),
    "PromptStrategy": (".core", "PromptStrategy"),
    "READONLY_EXPLORATION_TOOLS": (".loop_budget", "READONLY_EXPLORATION_TOOLS"),
    "RalphLoop": (".ralph", "RalphLoop"),
    "ReasoningDecision": (".reasoning", "Decision"),
    "ReasoningEngine": (".reasoning", "ReasoningEngine"),
    "ResourceBudget": (".resource_budget", "ResourceBudget"),
    "RuffBackend": (".lsp_feedback", "RuffBackend"),
    "Ruleset": (".permission", "Ruleset"),
    "SESSION_KEY": (".trusted_paths", "SESSION_KEY"),
    "SKILL_GIT_CLONE_TIMEOUT_SECONDS": (".skill_manager", "SKILL_GIT_CLONE_TIMEOUT_SECONDS"),
    "SKILL_INSTALL_CIRCUIT_COOLDOWN_SECONDS": (
        ".skill_manager",
        "SKILL_INSTALL_CIRCUIT_COOLDOWN_SECONDS",
    ),
    "SKILL_INSTALL_CIRCUIT_THRESHOLD": (".skill_manager", "SKILL_INSTALL_CIRCUIT_THRESHOLD"),
    "SSEEvent": (".sse_replay", "SSEEvent"),
    "SSESession": (".sse_replay", "SSESession"),
    "SSESessionRegistry": (".sse_replay", "SSESessionRegistry"),
    "SandboxExecutor": (".sandbox", "SandboxExecutor"),
    "SandboxPolicy": (".sandbox", "SandboxPolicy"),
    "SandboxResult": (".sandbox", "SandboxResult"),
    "SandboxVerdict": (".sandbox", "SandboxVerdict"),
    "ShellHook": (".hooks", "ShellHook"),
    "SkillManager": (".skill_manager", "SkillManager"),
    "StopHook": (".ralph", "StopHook"),
    "StreamJSONFormatter": (".output_formatter", "StreamJSONFormatter"),
    "SupervisorBrain": (".brain", "SupervisorBrain"),
    "TRAIT_MINING_PROMPT": (".trait_miner", "TRAIT_MINING_PROMPT"),
    "TRAIT_MINING_SYSTEM": (".trait_miner", "TRAIT_MINING_SYSTEM"),
    "Task": (".ralph", "Task"),
    "TaskResult": (".ralph", "TaskResult"),
    "TaskStatus": (".ralph", "TaskStatus"),
    "TextFormatter": (".output_formatter", "TextFormatter"),
    "TokenBudget": (".token_budget", "TokenBudget"),
    "ToolExecutor": (".tools", "ToolExecutor"),
    "ToolResultWithHint": (".tools", "ToolResultWithHint"),
    "ToolSkipped": (".tools", "ToolSkipped"),
    "TraitMiner": (".trait_miner", "TraitMiner"),
    "TypeScriptBackend": (".lsp_feedback", "TypeScriptBackend"),
    "UIConfirmBus": (".ui_confirm_bus", "UIConfirmBus"),
    "USER_PROFILE_ITEMS": (".user_profile", "USER_PROFILE_ITEMS"),
    "USER_PROFILE_KEY_ALIASES": (".user_profile", "USER_PROFILE_KEY_ALIASES"),
    "UserCancelledError": (".errors", "UserCancelledError"),
    "UserProfileItem": (".user_profile", "UserProfileItem"),
    "UserProfileManager": (".user_profile", "UserProfileManager"),
    "UserProfileState": (".user_profile", "UserProfileState"),
    "ValidationContext": (".validators", "ValidationContext"),
    "ValidationReport": (".validators", "ValidationReport"),
    "ValidationResult": (".validators", "ValidationResult"),
    "ValidatorOutput": (".validators", "ValidatorOutput"),
    "ValidatorRegistry": (".validators", "ValidatorRegistry"),
    "add_security_allowlist_entry": (".security_actions", "add_security_allowlist_entry"),
    "build_capability_id": (".capabilities", "build_capability_id"),
    "build_namespace": (".capabilities", "build_namespace"),
    "check_mode_permission": (".permission", "check_mode_permission"),
    "check_path": (".permission", "check_path"),
    "check_permission": (".permission", "check_permission"),
    "clear_session_trust": (".trusted_paths", "clear_session_trust"),
    "configure_docker": (".docker_backend", "configure_docker"),
    "consume_session_trust": (".trusted_paths", "consume_session_trust"),
    "create_budget_from_settings": (".resource_budget", "create_budget_from_settings"),
    "create_default_registry": (".validators", "create_default_registry"),
    "create_formatter": (".output_formatter", "create_formatter"),
    "detect_numeric_output": (".output_guard", "detect_numeric_output"),
    "detect_numeric_task": (".output_guard", "detect_numeric_task"),
    "estimate_tokens": (".context", "estimate_tokens"),
    "execute_controlled_action": (".security_actions", "execute_controlled_action"),
    "extract_working_facts": (".working_facts", "extract_working_facts"),
    "format_sse_frame": (".sse_replay", "format_sse_frame"),
    "format_working_facts": (".working_facts", "format_working_facts"),
    "get_audit_logger": (".audit", "get_audit_logger"),
    "get_confirmation_store": ("openakita.core.confirmation_state", "get_confirmation_store"),
    "get_docker_backend": (".docker_backend", "get_docker_backend"),
    "get_domain_allowlist": (".domain_allowlist", "get_domain_allowlist"),
    "get_hook_executor": (".hooks", "get_hook_executor"),
    "get_max_context_tokens": (".context", "get_max_context_tokens"),
    "get_pending_approvals_store": (".pending_approvals", "get_pending_approvals_store"),
    "get_primary_agent": (".core", "get_primary_agent"),
    "get_profile_manager": (".user_profile", "get_profile_manager"),
    "get_registry": (".sse_replay", "get_registry"),
    "get_sandbox_executor": (".sandbox", "get_sandbox_executor"),
    "get_session_overrides": (".trusted_paths", "get_session_overrides"),
    "get_ui_confirm_bus": (".ui_confirm_bus", "get_ui_confirm_bus"),
    "grant_session_trust": (".trusted_paths", "grant_session_trust"),
    "is_trusted_workspace_path": (".trusted_paths", "is_trusted_workspace_path"),
    "list_security_allowlist": (".security_actions", "list_security_allowlist"),
    "list_skill_external_allowlist": (".security_actions", "list_skill_external_allowlist"),
    "maybe_broadcast_death_switch_reset": (
        ".security_actions",
        "maybe_broadcast_death_switch_reset",
    ),
    "maybe_refresh_skills": (".security_actions", "maybe_refresh_skills"),
    "merge_working_facts": (".working_facts", "merge_working_facts"),
    "normalize_confirmation_answer": (".confirmation", "normalize_confirmation_answer"),
    "normalize_slug": (".capabilities", "normalize_slug"),
    "notify_task_completed": (".desktop_notify", "notify_task_completed"),
    "notify_task_completed_async": (".desktop_notify", "notify_task_completed_async"),
    "parse_last_event_id": (".sse_replay", "parse_last_event_id"),
    "parse_token_budget": (".token_budget", "parse_token_budget"),
    "persist_trait_to_memory": (".persona", "persist_trait_to_memory"),
    "remove_security_allowlist_entry": (".security_actions", "remove_security_allowlist_entry"),
    "reset_audit_logger": (".audit", "reset_audit_logger"),
    "reset_death_switch": (".security_actions", "reset_death_switch"),
    "reset_pending_approvals_store": (".pending_approvals", "reset_pending_approvals_store"),
    "reset_registry_for_testing": (".sse_replay", "reset_registry_for_testing"),
    "reset_ui_confirm_bus": (".ui_confirm_bus", "reset_ui_confirm_bus"),
    "resolve_profile_key": (".user_profile", "resolve_profile_key"),
    "save_overflow": (".tools", "save_overflow"),
    "send_desktop_notification": (".desktop_notify", "send_desktop_notification"),
    "send_desktop_notification_async": (".desktop_notify", "send_desktop_notification_async"),
    "set_hook_executor": (".hooks", "set_hook_executor"),
    "set_primary_agent": (".core", "set_primary_agent"),
    "set_skill_external_allowlist": (".security_actions", "set_skill_external_allowlist"),
    "smart_truncate": (".tools", "smart_truncate"),
    "truncate_tool_result": (".tool_result_budget", "truncate_tool_result"),
    "validate_no_fabricated_numbers": (".output_guard", "validate_no_fabricated_numbers"),
}


def __getattr__(name: str):
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, symbol = target
    value = getattr(import_module(module, __name__), symbol)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))
